image: registry.gitlab.com/itk.fr/lorhammer/build

before_script:
    - ln -s /builds/$CI_PROJECT_PATH /go/src/lorhammer
    - cd /go/src/lorhammer
    - sh install.sh

stages:
    - lint
    - test
    - integration
    - compile
    - doc

lint:gofmt:
    stage: lint
    script:
        - diff -u <(echo -n) <(gofmt -d ./src)
        - if [ $? -eq 0 ]; then echo "code formatted"; else echo "run > gofmt -w -d ./src" && exit 1; fi

lint:vet:
    stage: lint
    script:
        - go tool vet -composites=false -shadow=true src/**/*.go

test:unit:
    stage: test
    script:
        - go test -race $(go list ./src/...)

test:coverage:
    stage: test
    coverage: /total[^\d]+(\d+.\d+\%)/
    script:
        - ./resources/scripts/cover.sh -terminal

.integration: &integration
  stage: integration
  services:
    - docker:dind
  script:
    - LORHAMMER_PROMETHEUS_IP="prometheus" LORHAMMER_MQTT_IP="mqtt" LORHAMMER_CONSUL_IP="consul" LORHAMMER_GRAFANA_IP="grafana" ./resources/scripts/launchTools.sh
    - sleep 10
    - echo "Start 1 lorhammer"
    - docker-compose -f docker-compose.yml -f docker-compose.integration.yml -p ${CI_BUILD_ID} up -d lorhammer
    - sleep 30
    - echo "Start orchestrator to launch scenario and check all is ok"
    - docker-compose -f docker-compose.yml -f docker-compose.integration.yml -p ${CI_BUILD_ID} run orchestrator
    - echo "All is ok clean docker deamon"
    - docker-compose -p ${CI_BUILD_ID} down --remove-orphans
  tags:
    - docker

integration:oneShot:
  <<: *integration
  variables:
    FROM_FILE: "./resources/scenarios/ci/ci-integration-oneShot.json"
    DOCKER_HOST: "tcp://docker:2375"
    COMPOSE_HTTP_TIMEOUT: "200"

integration:ramp:
  <<: *integration
  variables:
    FROM_FILE: "./resources/scenarios/ci/ci-integration-ramp.json"
    DOCKER_HOST: "tcp://docker:2375"
    COMPOSE_HTTP_TIMEOUT: "200"

integration:repeat:
  <<: *integration
  variables:
    FROM_FILE: "./resources/scenarios/ci/ci-integration-repeat.json"
    DOCKER_HOST: "tcp://docker:2375"
    COMPOSE_HTTP_TIMEOUT: "200"

compile:all:
  stage: compile
  script:
    - sh ./resources/scripts/buildAllEnv.sh
  only:
    - master@itk.fr/lorhammer
  artifacts:
    paths:
      - build
    expire_in: 1 week

compile:docker:
  stage: compile
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/itk.fr/lorhammer/lorhammer docker/lorhammer/.
    - docker push registry.gitlab.com/itk.fr/lorhammer/lorhammer
  only:
    - master@itk.fr/lorhammer
  variables:
    DOCKER_HOST: "tcp://docker:2375"

compile:tag:
  stage: compile
  script:
    - sh ./resources/scripts/buildAllEnv.sh
  only:
    - tags
  artifacts:
    paths:
      - build

pages:
  stage: doc
  script:
    - resources/scripts/makeDoc.sh
    - rm -rf doc/public
    - mv doc/public_min public
  artifacts:
    paths:
      - public
  only:
    - master
