version: '2'

services:

  lorhammer:
    build:
      context: .
      dockerfile: ./docker/lorhammer/Dockerfile
    command: -consul consul:8500 -local-ip lorhammer
    entrypoint: /lorhammer
    depends_on:
      - consul
      - mqtt

  orchestrator:
    build:
      context: .
      dockerfile: ./docker/lorhammer/Dockerfile
    volumes:
      - ./resources:/resources
    command: -consul consul:8500 -from-file "${FROM_FILE}"
    depends_on:
      - consul
      - mqtt
      - prometheus
