version: '2'

services:

  lorhammer:
    image: ${CI_REGISTRY_IMAGE}/lorhammer:${CI_PIPELINE_ID}
    command: -consul consul:8500 -local-ip lorhammer -vvv
    depends_on:
      - consul
      - mqtt

  orchestrator:
    image: ${CI_REGISTRY_IMAGE}/orchestrator:${CI_PIPELINE_ID}
    command: -consul consul:8500 -from-file "${FROM_FILE}"
    volumes:
      - ./resources/scenarios/ci/:/resources/scenarios/ci/
    depends_on:
      - consul
      - mqtt
      - prometheus
