project_name: lorhammer
builds:
  - binary: lorhammer
    main: ./src/lorhammer/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - binary: orchestrator
    main: ./src/orchestrator/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64